from flask import Flask, redirect, url_for, session, request, jsonify, render_template_string
import requests
import random
import time
import sqlite3
import os
from urllib.parse import quote

app = Flask(__name__)
app.secret_key = "SUPER_SECRET_CHANGE_THIS_123456789"

# CHANGE THESE 3 LINES!!!
DISCORD_CLIENT_ID = "YOUR_DISCORD_CLIENT_ID"
DISCORD_CLIENT_SECRET = "YOUR_DISCORD_CLIENT_SECRET"
DISCORD_REDIRECT_URI = "https://your-panel.onrender.com/callback"  # Will update after deploy

# Only allow these Discord IDs (your staff)
ALLOWED_DISCORD_IDS = [
    123456789012345678,   # ← Your Discord ID
    987654321098765432,   # ← Staff 1
    # Add all your staff Discord IDs here
]

DB = "pins.db"

def init_db():
    with sqlite3.connect(DB) as conn:
        conn.execute('''CREATE TABLE IF NOT EXISTS pins (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            pin TEXT UNIQUE,
            generated_by TEXT,
            generated_by_id TEXT,
            generated_at INTEGER,
            used INTEGER DEFAULT 0,
            used_by TEXT,
            used_hwid TEXT,
            used_pc TEXT,
            used_at INTEGER,
            expires INTEGER
        )''')

def get_user_info(code):
    data = {
        'client_id': DISCORD_CLIENT_ID,
        'client_secret': DISCORD_CLIENT_SECRET,
        'grant_type': 'authorization_code',
        'code': code,
        'redirect_uri': DISCORD_REDIRECT_URI,
        'scope': 'identify'
    }
    headers = {'Content-Type': 'application/x-www-form-urlencoded'}
    r = requests.post("https://discord.com/api/oauth2/token", data=data, headers=headers)
    if r.status_code != 200:
        return None
    credentials = r.json()
    token = credentials['access_token']
    user = requests.get("https://discord.com/api/users/@me", headers={"Authorization": f"Bearer {token}"})
    return user.json() if user.status_code == 200 else None

HTML = """
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>NEXUS ANTICHEAT - Admin Panel</title>
  <style>
    body { background:#0f0f0f; color:#fff; font-family:'Segoe UI'; margin:0; padding:20px; }
    .container { max-width:1100px; margin:auto; }
    header { text-align:center; padding:30px; background:linear-gradient(45deg,#ff3333,#990000); border-radius:15px; margin-bottom:30px; }
    .card { background:#1a1a1a; padding:25px; border-radius:12px; margin:20px 0; }
    button { padding:18px 40px; font-size:22px; background:#ff3333; border:none; border-radius:12px; color:white; cursor:pointer; }
    button:hover { background:#ff5555; }
    #pin { font-size:70px; color:#00ff00; margin:40px 0; }
    table { width:100%; border-collapse:collapse; margin-top:20px; }
    th, td { padding:15px; text-align:left; border-bottom:1px solid #333; }
    th { background:#ff3333; }
    .logout { float:right; background:#333; font-size:14px; padding:10px 20px; }
    .user { color:#00ff00; font-weight:bold; }
  </style>
</head>
<body>
<div class="container">
  <header>
    <h1>NEXUS ANTICHEAT</h1>
    <h2>Staff Panel - <span class="user">{{ username }}#{{ discriminator }}</span>
    <a href="/logout" class="logout">Logout</a></h2>
  </header>

  <div class="card">
    <h2>Generate Screenshot PIN</h2>
    <button onclick="gen()">GENERATE NEW PIN</button>
    <div id="pin">Click button above</div>
  </div>

  <div class="card">
    <h2>PIN History (Last 50)</h2>
    <table>
      <tr>
        <th>PIN</th>
        <th>Generated By</th>
        <th>Time</th>
        <th>Status</th>
        <th>Used By (PC)</th>
        <th>HWID</th>
      </tr>
      {% for p in pins %}
      <tr style="background:{{ '#2a0000' if p.used else '#002200' }}">
        <td><b>{{ p.pin }}</b></td>
        <td>{{ p.generated_by }}#{{ p.generated_by_id[-4:] }}</td>
        <td>{{ p.time }}</td>
        <td>{{ 'USED' if p.used else 'ACTIVE' }}</td>
        <td>{{ p.used_pc or '-' }}</td>
        <td>{{ (p.used_hwid[:16] + '...') if p.used_hwid else '-' }}</td>
      </tr>
      {% endfor %}
    </table>
  </div>
</div>

<script>
function gen() {
  fetch('/generate', {method:'POST'})
  .then(r => r.json())
  .then(d => {
    document.getElementById("pin").innerHTML = "<b>" + d.pin + "</b><br><small>Expires in 10 minutes</small>";
  });
}
setInterval(() => location.reload(), 30000); // Auto refresh every 30s
</script>
</body>
</html>
"""

LOGIN_HTML = '''
<!DOCTYPE html>
<html>
<head>
  <title>Nexus SS - Discord Login</title>
  <style>
    body { background:#000; color:#fff; display:flex; justify-content:center; align-items:center; height:100vh; margin:0; font-family:Arial; }
    .box { text-align:center; background:#111; padding:60px; border-radius:20px; box-shadow:0 0 30px #ff3333; }
    h1 { color:#ff3333; }
    button { margin-top:30px; padding:20px 50px; background:#5865F2; border:none; border-radius:12px; color:white; font-size:20px; cursor:pointer; }
  </style>
</head>
<body>
<div class="box">
  <h1>NEXUS ANTICHEAT</h1>
  <h2>Staff Login</h2>
  <p>Login with Discord to access the panel</p>
  <a href="{{ login_url }}"><button>LOGIN WITH DISCORD</button></a>
</div>
</body>
</html>
'''

@app.route("/")
def index():
    if "user" in session:
        return redirect("/panel")
    oauth_url = f"https://discord.com/api/oauth2/authorize?client_id={DISCORD_CLIENT_ID}&redirect_uri={quote(DISCORD_REDIRECT_URI)}&response_type=code&scope=identify"
    return render_template_string(LOGIN_HTML, login_url=oauth_url)

@app.route("/callback")
def callback():
    code = request.args.get("code")
    if not code:
        return "Access denied", 403
    user = get_user_info(code)
    if not user or int(user["id"]) not in ALLOWED_DISCORD_IDS:
        return "<h1 style='color:red;text-align:center;margin-top:100px'>Access Denied<br>Only authorized staff</h1>", 403
    
    session["user"] = user
    return redirect("/panel")

@app.route("/panel")
def panel():
    if "user" not in session:
        return redirect("/")
    
    user = session["user"]
    with sqlite3.connect(DB) as conn:
        conn.row_factory = sqlite3.Row
        pins = conn.execute("""
            SELECT *, 
                   datetime(generated_at, 'unixepoch') as time,
                   datetime(used_at, 'unixepoch') as used_time
            FROM pins ORDER BY id DESC LIMIT 50
        """).fetchall()
    
    return render_template_string(HTML, username=user["username"], discriminator=user["discriminator"], pins=pins)

@app.route("/generate", methods=["POST"])
def generate():
    if "user" not in session:
        return jsonify({"error": "unauthorized"}), 403
    
    user = session["user"]
    pin = f"{random.randint(100000,999999)}"
    expires = int(time.time()) + 600
    
    with sqlite3.connect(DB) as conn:
        conn.execute("""INSERT INTO pins 
            (pin, generated_by, generated_by_id, generated_at, expires) 
            VALUES (?, ?, ?, ?, ?)""",
            (pin, user["username"], user["discriminator"], int(time.time()), expires))
    
    return jsonify({"pin": pin})

@app.route("/validate", methods=["POST"])
def validate():
    data = request.get_json() or {}
    pin = data.get("pin")
    hwid = data.get("hwid")
    pc_name = data.get("pc", "Unknown")
    
    with sqlite3.connect(DB) as conn:
        c = conn.cursor()
        c.execute("SELECT * FROM pins WHERE pin=? AND used=0 AND expires>?", (pin, int(time.time())))
        row = c.fetchone()
        if row:
            conn.execute("""UPDATE pins SET 
                used=1, used_by=?, used_hwid=?, used_pc=?, used_at=? 
                WHERE pin=?""", 
                (session.get("user", {}).get("username", "Player"), hwid, pc_name, int(time.time()), pin))
            return jsonify({"valid": True})
    return jsonify({"valid": False}), 403

@app.route("/logout")
def logout():
    session.clear()
    return redirect("/")

if __name__ == "__main__":
    init_db()
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port)